//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnpUtilGui.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PnpUtilGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention.
        /// </summary>
        internal static string Form1_DeleteButton_Click_MessageBox_Caption {
            get {
                return ResourceManager.GetString("Form1_DeleteButton_Click_MessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you really want to delete {0} drivers?.
        /// </summary>
        internal static string Form1_DeleteButton_Click_MessageBoxText {
            get {
                return ResourceManager.GetString("Form1_DeleteButton_Click_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No drivers selected. Check the checkbox of the driver(s) first..
        /// </summary>
        internal static string Form1_NoDriversSelected_Message {
            get {
                return ResourceManager.GetString("Form1_NoDriversSelected_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Select all.
        /// </summary>
        internal static string Form1_SelectAllCheckBox_Text {
            get {
                return ResourceManager.GetString("Form1_SelectAllCheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Signer.
        /// </summary>
        internal static string Form1_Column_CertificateSignerName {
            get {
                return ResourceManager.GetString("Form1_Column_CertificateSignerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checked.
        /// </summary>
        internal static string Form1_Column_Checked {
            get {
                return ResourceManager.GetString("Form1_Column_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class GUID.
        /// </summary>
        internal static string Form1_Column_ClassGuid {
            get {
                return ResourceManager.GetString("Form1_Column_ClassGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date / Version.
        /// </summary>
        internal static string Form1_Column_DateAndVersion {
            get {
                return ResourceManager.GetString("Form1_Column_DateAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class.
        /// </summary>
        internal static string Form1_Column_DriverClass {
            get {
                return ResourceManager.GetString("Form1_Column_DriverClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Published Name.
        /// </summary>
        internal static string Form1_Column_FileName {
            get {
                return ResourceManager.GetString("Form1_Column_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Provider.
        /// </summary>
        internal static string Form1_Column_Publisher {
            get {
                return ResourceManager.GetString("Form1_Column_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Original Name.
        /// </summary>
        internal static string Form1_Column_SourceName {
            get {
                return ResourceManager.GetString("Form1_Column_SourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Driver: {0}.
        /// </summary>
        internal static string Form1_LogDriver {
            get {
                return ResourceManager.GetString("Form1_LogDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error deleting driver {0}: {1}.
        /// </summary>
        internal static string Form1_LogErrorDeleting {
            get {
                return ResourceManager.GetString("Form1_LogErrorDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error exporting driver {0}: {1}.
        /// </summary>
        internal static string Form1_LogErrorExporting {
            get {
                return ResourceManager.GetString("Form1_LogErrorExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exporting {0} driver(s) to {1}.
        /// </summary>
        internal static string Form1_LogExporting {
            get {
                return ResourceManager.GetString("Form1_LogExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [pnputil.exe exited with code {0}].
        /// </summary>
        internal static string PnpUtilHelper_ExitedWithCode {
            get {
                return ResourceManager.GetString("PnpUtilHelper_ExitedWithCode", resourceCulture);
            }
        }
    }
}
